# Generated by Django 5.0 on 2023-12-23 03:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0007_remove_comentario_imagen_publicacion_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='me_gusta',
            field=models.ManyToManyField(blank=True, related_name='posteos', to=settings.AUTH_USER_MODEL),
        ),
    ]
